eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:9066/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 9088
  servlet:
    context-path: /rank

spring:
  application:
    name: rank-server


  datasource:
    url: jdbc:mysql://192.168.2.244:3306/performance_distribut?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: dev
    password: dev@MySQL123

  jpa:
    hibernate:
      ddl-auto: none
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
        generate_statistics: false
        max_fetch_depth: 0

      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE








